### ISSUE TITLE
Optionally drawing high-speed rail curves, rounded, below city level

### ISSUE THREAD

**Issue by theworldisnotflat** [theworldisnotflat/shriveling_world#56] opened 2019-03-01 22:29 UTC
rounded or not rounded, optionally

- in case of complex cones, HST should be below, not rounded, but allowing for aerial to remain rounded
- should be as a checkBox at the transport mode level in the interface

**Comment by alainlhostis** [comment] 2021-02-01 20:39
duplicate of issue #103

**Closed by alainlhostis** 2021-02-01 20:39 UTC
Labels: new functionality
